nodeLinker: node-modules
enableTelemetry: 0
approvedGitRepositories:
  - "https://github.com/cozy/*"
  - "https://github.com/linagora/*"
  - "https://github.com/konnectors/*"
npmPreapprovedPackages:
  - "@linagora/*"
  - "@cozy/*"
  - "cozy-*"
  - "twake-*"
  - "babel-preset-cozy-app"
  - "rsbuild-config-cozy-app"
  - "stylus-config-cozy-app"
  - "browserslist-config-cozy"
  - "eslint-config-cozy-app"
