name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

permissions:
  contents: read

jobs:
  build:
    uses: linagora/twake-workflows/.github/workflows/build-and-publish-cozy-app.yml@a8c34c5fbc87363445cd1f2128b8be9000bbf49f # v1.0.0
    with:
      mattermost-channel: '{"dev":"app---settings","beta":"app---settings,publication","stable":"app---settings,publication"}'
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      DOWNCLOUD_SSH_KEY: ${{ secrets.DOWNCLOUD_SSH_KEY }}
      MATTERMOST_HOOK_URL: ${{ secrets.MATTERMOST_HOOK_URL }}
